### Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### Importing the Dataset

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url,names=colnames)

### Preprocessing

In [5]:
X = irisdata.drop(["Class"],axis =1)
y = irisdata['Class']

### Train Test Split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

### Training the Algorithm
1. Polynomial Kernel

In [9]:
from sklearn.svm import SVC
svclassifier = SVC(kernel="poly", degree=8)
svclassifier.fit(X_train,y_train)

C:\Users\ArunVignesh\Anaconda3_2019\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

Making Predictions

In [10]:
y_pred = svclassifier.predict(X_test)

Evaluating the Algorithm

In [23]:
from sklearn.metrics import classification_report, confusion_matrix

# Confusion Matrix
print("Confusion Matrix",confusion_matrix(y_test,y_pred))
print( "\n***************************\n")
#Classification Report
print("Classification Report", classification_report(y_test,y_pred))

Confusion Matrix [[11  0  0]
 [ 0  7  2]
 [ 0  0 10]]

***************************

Classification Report                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.78      0.88         9
 Iris-virginica       0.83      1.00      0.91        10

      micro avg       0.93      0.93      0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30



2. Gaussian Kernel

In [29]:
from sklearn.svm import SVC
svcclassifier = SVC(kernel="rbf")
svcclassifier.fit(X_train,y_train)

C:\Users\ArunVignesh\Anaconda3_2019\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

Prediction and Evaluation

In [30]:
# Predict the test data
y_pred = svcclassifier.predict(X_test)

# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix

# Confusion Matrix
print("Confusion Matrix",confusion_matrix(y_test,y_pred))
print( "\n***************************\n")
#Classification Report
print("Classification Report", classification_report(y_test,y_pred))

Confusion Matrix [[11  0  0]
 [ 0  7  2]
 [ 0  0 10]]

***************************

Classification Report                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.78      0.88         9
 Iris-virginica       0.83      1.00      0.91        10

      micro avg       0.93      0.93      0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30



3. Sigmoid Kernel

In [26]:
from sklearn.svm import SVC
svcclassifier = SVC(kernel="sigmoid")
svcclassifier.fit(X_train,y_train)

C:\Users\ArunVignesh\Anaconda3_2019\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

Prediction and Evaluation

In [27]:
# Predict the test data
y_pred = svcclassifier.predict(X_test)

# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix

# Confusion Matrix
print("Confusion Matrix",confusion_matrix(y_test,y_pred))
print( "\n***************************\n")
#Classification Report
print("Classification Report", classification_report(y_test,y_pred))

Confusion Matrix [[ 0 11  0]
 [ 0  9  0]
 [ 0 10  0]]

***************************

Classification Report                  precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        11
Iris-versicolor       0.30      1.00      0.46         9
 Iris-virginica       0.00      0.00      0.00        10

      micro avg       0.30      0.30      0.30        30
      macro avg       0.10      0.33      0.15        30
   weighted avg       0.09      0.30      0.14        30



C:\Users\ArunVignesh\Anaconda3_2019\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
